SHOW user;

SELECT * FROM EMPLOYEES;

SELECT employee_id,  last_name FROM employees;

SELECT last_name, salary, salary +1000 FROM employees;

SELECT first_name||' '||last_name FROM EMPLOYEES;  --concatination operator--

SELECT DISTINCT JOB_ID FROM JOB_HISTORY;

SELECT FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES
WHERE FIRST_NAME='Neena';

SELECT FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE >'31-DEC-05';

SELECT FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES
WHERE SALARY BETWEEN 15000 AND 50000;

SELECT FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '1-JAN-98' AND '31-DEC-05'; --BETWEEN/AND OPERATOR--

SELECT FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES
WHERE FIRST_NAME BETWEEN 'A' AND 'C';

SELECT FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (80,90,100 );   --IN OPERATOR--

SELECT FIRST_NAME,LAST_NAME SALARY, HIRE_DATE FROM EMPLOYEES
WHERE LAST_NAME IN 'King';

SELECT FIRST_NAME,LAST_NAME SALARY, HIRE_DATE FROM EMPLOYEES
WHERE LAST_NAME IN 'King';

SELECT FIRST_NAME,LAST_NAME SALARY, HIRE_DATE FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_ia%';  ---LIKE OPERATOR USING PATTERN---

SELECT FIRST_NAME,LAST_NAME SALARY, HIRE_DATE FROM EMPLOYEES
WHERE DEPARTMENT_ID IS null; --IS USER FOR NULL

--------------SNIPPETS AND FUNCTIONS------------------------------------------------
SELECT UPPER('HELLO') FROM DUAL; 

SELECT INITCAP('HEllLO') FROM DUAL;

SELECT FIRST_NAME,LAST_NAME, LENGTH(FIRST_NAME)  FROM EMPLOYEES
WHERE DEPARTMENT_ID = 100;

SELECT FIRST_NAME, SUBSTR(FIRST_NAME, 2, 1) FROM EMPLOYEES;

SELECT CONCAT(FIRST_NAME, LAST_NAME) FROM EMPLOYEES;

SELECT RPAD('HELLO', 12, '?') FROM DUAL;

SELECT LTRIM('HELLO WORLD', 'H') FROM DUAL;

SELECT TRIM('H' FROM 'HHHELOHHH') FROM DUAL;

SELECT ROUND(29.8878, 2) FROM DUAL;

SELECT TRUNC(29.8878) FROM DUAL;

SELECT ABS(-5.66) FROM DUAL;

SELECT MOD(11,4) FROM DUAL;

--------------TIME AND DATE FUNCTIONS----------------------

SELECT TO_DATE('12-MARCH-17') + 3 FROM DUAL;

SELECT SYSTIMESTAMP FROM DUAL;

SELECT  ADD_MONTHS('2-MAY-10', 4)FROM DUAL;

SELECT  ADD_MONTHS('2-MAY-10', 4)FROM DUAL;

-----------------NVL FUNCTION-----------------------

SELECT  FIRST_NAME, NVL(TO_CHAR(COMMISSION_PCT),'NA') FROM EMPLOYEES
WHERE JOB_ID IN ('AD_VP', 'SA_MAN');

























