SHOW user;
SELECT * FROM EMPLOYEES;
SELECT employee_id,  last_name FROM employees;
SELECT last_name, salary, salary +1000 FROM employees;
SELECT first_name||' '||last_name FROM EMPLOYEES;  --concatination operator--
SELECT FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES
WHERE FIRST_NAME='Neena';

SELECT FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE >'31-DEC-05';

SELECT FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES
WHERE SALARY BETWEEN 15000 AND 50000;

SELECT FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE BETWEEN '1-JAN-98' AND '31-DEC-05';

SELECT FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES
WHERE FIRST_NAME BETWEEN 'A' AND 'C';

SELECT FIRST_NAME, SALARY, HIRE_DATE FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (80,90,100 );

SELECT FIRST_NAME,LAST_NAME SALARY, HIRE_DATE FROM EMPLOYEES
WHERE LAST_NAME IN 'King';

SELECT FIRST_NAME,LAST_NAME SALARY, HIRE_DATE FROM EMPLOYEES
WHERE LAST_NAME IN 'King';

SELECT FIRST_NAME,LAST_NAME SALARY, HIRE_DATE FROM EMPLOYEES
WHERE FIRST_NAME LIKE '_i%';  ---LIKE OPERATOR USING PATTERN---






